"""add_indicator_logs

Revision ID: bc159b538704
Revises: 0004
Create Date: 2026-05-08 17:12:53.774991

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc159b538704"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicator_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("algo_name", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("interval", sa.String(), nullable=False),
        sa.Column("chart", sa.String(), nullable=False),
        sa.Column("series", sa.String(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indicator_logs_algo_name"), "indicator_logs", ["algo_name"], unique=False
    )
    op.create_index(
        op.f("ix_indicator_logs_session_id"), "indicator_logs", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_indicator_logs_symbol"), "indicator_logs", ["symbol"], unique=False)
    op.create_index(op.f("ix_indicator_logs_ts"), "indicator_logs", ["ts"], unique=False)
    op.drop_constraint(op.f("orders_signal_id_fkey"), "orders", type_="foreignkey")
    op.create_foreign_key(None, "orders", "signals", ["signal_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_signal_id_fkey", "orders", type_="foreignkey")
    op.create_foreign_key(
        op.f("orders_signal_id_fkey"),
        "orders",
        "signals",
        ["signal_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_indicator_logs_ts"), table_name="indicator_logs")
    op.drop_index(op.f("ix_indicator_logs_symbol"), table_name="indicator_logs")
    op.drop_index(op.f("ix_indicator_logs_session_id"), table_name="indicator_logs")
    op.drop_index(op.f("ix_indicator_logs_algo_name"), table_name="indicator_logs")
    op.drop_table("indicator_logs")
    # ### end Alembic commands ###
