from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class RollingStateCacheRow(Base):
    """
    Durable backing store for PostgresKVCache (trading-platform#79) --
    generic key/value rows, used today only by RollingStateCacher so a
    process restart no longer silently discards a strategy's in-progress
    rolling state (see storage/cache/postgres_backend.py).

    This is a 9th per-module Base/metadata object, on top of the 8 that
    trading-platform#35 already flags as a live schema-drift risk --
    noted deliberately rather than silently adding to that count. It
    doesn't carry #35's actual risk though: #35 is about *duplicate*
    models mapping the *same* table under two disagreeing definitions,
    and this table is brand new with no competing copy anywhere, no
    relationships to any other table, and its one migration is
    hand-written (see alembic/versions/0011_*), not autogenerated. It
    exists as an ORM model purely so trading.app.database.init_db()'s
    existing per-Base create_all() sweep creates it in tests like every
    other table, matching this codebase's established test-infra
    convention rather than inventing a new one for a single table.
    """

    __tablename__ = "rolling_state_cache"

    key: Mapped[str] = mapped_column(String, primary_key=True)
    value: Mapped[str] = mapped_column(Text)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
